#pragma once

// From glfw3.h
#define ARIA_MOUSE_BUTTON_1         0
#define ARIA_MOUSE_BUTTON_2         1
#define ARIA_MOUSE_BUTTON_3         2
#define ARIA_MOUSE_BUTTON_4         3
#define ARIA_MOUSE_BUTTON_6         5
#define ARIA_MOUSE_BUTTON_5         4
#define ARIA_MOUSE_BUTTON_7         6
#define ARIA_MOUSE_BUTTON_8         7
#define ARIA_MOUSE_BUTTON_LAST      ARIA_MOUSE_BUTTON_8
#define ARIA_MOUSE_BUTTON_LEFT      ARIA_MOUSE_BUTTON_1
#define ARIA_MOUSE_BUTTON_RIGHT     ARIA_MOUSE_BUTTON_2
#define ARIA_MOUSE_BUTTON_MIDDLE    ARIA_MOUSE_BUTTON_3